# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unab', '0002_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='whatever')),
            ],
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='foto',
        ),
    ]
