# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unab', '0003_auto_20170623_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='titulo',
            new_name='name',
        ),
    ]
