# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unab', '0005_auto_20170623_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contenido', models.TextField()),
                ('sort_order', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unab.Category')),
            ],
        ),
    ]
