# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unab', '0007_auto_20170623_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
